# create an in Numpy and perform basic operations on the array using Numpy. such as reshaping, indexing, slicing, and iterating.

# joing operation

In [1]:
import numpy as np 
arr = np.array ([1, 2, 3, 4, 5])
print (arr)


[1 2 3 4 5]


# joing operation

In [2]:
  arr = np.array ([1, 2, 3, 4])
  print (arr[2] + arr[3])

7


# array indexing

In [3]:
arr = np.array ([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print ('2nd element on 1st row: ', arr[0, 1])
arr = np.array ([1, 2, 3, 4], ndmin = 5)

2nd element on 1st row:  2


# Type of Array

In [4]:
 print (type (arr))

<class 'numpy.ndarray'>


# shape of array

In [5]:
print (arr)
print ('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# reshape of array

In [6]:
  arr = np.array ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
  newarr = arr.reshape (4, 3)
  print (newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# slicing of array

In [7]:
arr = np.array ([1, 2, 3, 4, 5, 6, 7])
print (arr[:4])


[1 2 3 4]


# iterating of array

In [8]:
 import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6
